### PR TITLE
Add factory methods to create an enum bit mask

### PR DESCRIPTION
**Pull request by gisostallenberg**
* Add a method to create a bit mask using one or multiple cases
* Add a method to create a bit mask using all cases
* Add a method to create a bit mask with no flags on
* Add a method to create a bit mask without some flags

### CODE REVIEW

**Comment by yaroslavche** [comment]
Looks ok to me.
Please fix docblocks regarding following rules:
if the docblock consists of one line, make it one line
do not repeat the method signature in the docblock (if the method returns self/static, you do not need to duplicate this information in the docblock)

**Comment by yaroslavche** [comment]
None is same as skip second argument in base factory method. Is it needed anyway?

**Comment by yaroslavche** [comment]
@gisostallenberg In general, I agree with you. That makes sense. I've just waited for your opinion on that (sorry, that didn't tag you).

Regarding the use of `static`/`$this` in DocBlocks, I believe the method signature already indicates whether a method is static or not, making it unnecessary to duplicate this information in the DocBlock. A static method will never return `$this`, so there is no need to specify it explicitly in the DocBlock. Additionally, since the `EnumBitMask` class is `final`, the `static` keyword is redundant.
I aim to maintain clean and concise documentation without unnecessary duplication. However, I might be wrong in some aspects.

I will update the DocBlocks to make @throws consistent with others, add documentation to the README, and then merge the changes and make a new release. Thank you for your contribution.

**Comment by gisostallenberg** [comment]
> I aim to maintain clean and concise documentation without unnecessary duplication. However, I might be wrong in some aspects.

You are right in the aspects of static methods not returning `$this` and that `self` is better for a final class.

I only added the docblock for `$this` return type in `EnumBitMask::set` and `EnumBitMask::remove`, where I think they have added value. See https://github.com/yaroslavche/BitMask/pull/31/commits/35d40b26c0e02c4278368e8c4bc12cd84a320958#diff-65d7c807c5a88226a7bc83369db7e5a2b25614c48428227993607486b49fb1c8R95

Thanks for merging!

Will you release a new version?

**Comment by yaroslavche** [comment]
@gisostallenberg 
> Will you release a new version?

yes, I've already added a new release: [v3.0.2](https://github.com/yaroslavche/BitMask/releases/tag/v3.0.2)

> I only added the docblock for $this return type in EnumBitMask::set and EnumBitMask::remove

My reasoning behind this change is as follows: With this PR, the final class now includes static factory methods that consistently return a new object of the class, which aligns with the expected behavior of factory methods. Conversely, when a non-static method returns self (and not a cloned instance), it indicates that the method operates on and returns the same object instance that invoked it.

**Comment by gisostallenberg** [comment]
> yes, I've already added a new release: [v3.0.2](https://github.com/yaroslavche/BitMask/releases/tag/v3.0.2)

Thanks!!

> My reasoning behind this change is as follows: With this PR, the final class now includes static factory methods that consistently return a new object of the class, which aligns with the expected behavior of factory methods. Conversely, when a non-static method returns self (and not a cloned instance), it indicates that the method operates on and returns the same object instance that invoked it.

Sure. I agree. Besides that one can use the `EnumBitMask::set` and `EnumBitMask::remove` methods on an actual instance and in that case it would be a nice addition. But off course it is just a nice to have.


Thank you so much for your time spend on this PR 🙏🏽 .

**Comment by yaroslavche** [comment]
Thank you for your efforts! Really appreciate it <3

**Pull request merged**
